tap "exolnet/deprecated"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "sambadevi/powerlevel9k"
brew "openssl@1.1"
brew "autoconf"
brew "node"
brew "babel"
brew "cask"
brew "composer"
brew "cups"
brew "openldap"
brew "dnsmasq", restart_service: true
brew "fzf"
brew "gitversion"
brew "htop"
brew "httpd", restart_service: true
brew "imagemagick"
brew "libiconv"
brew "mariadb", restart_service: true
brew "mas"
brew "php", link: false
brew "php@7.2"
brew "php@7.3", link: true
brew "phpunit"
brew "pkg-config"
brew "python", link: false
brew "qcachegrind"
brew "rbenv"
brew "redis", restart_service: true
brew "ssh-copy-id"
brew "supervisor"
brew "unittest"
brew "wget"
brew "yarn"
brew "zsh-autosuggestions"
brew "exolnet/deprecated/php@5.6"
brew "exolnet/deprecated/php@7.1"
brew "sambadevi/powerlevel9k/powerlevel9k"
cask "alfred"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-awesome-terminal-fonts"
cask "font-fontawesome"
cask "font-hack-nerd-font"
cask "font-source-code-pro"
cask "google-chrome"
cask "grandperspective"
cask "insomnia"
cask "iterm2"
cask "kap"
cask "microsoft-office"
cask "postman"
cask "rowanj-gitx"
cask "spotify"
cask "sublime-merge"
cask "sublime-text"
cask "tableplus"
cask "transmit"
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
