tap "exolnet/deprecated"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
# Automatic configure script builder
brew "autoconf"
# Platform built on V8 to build network applications
brew "node"
# Compiler for writing next generation JavaScript
brew "babel"
# Emacs dependency management
brew "cask"
# Dependency Manager for PHP
brew "composer"
# Common UNIX Printing System
brew "cups"
# Lightweight DNS forwarder and DHCP server
brew "dnsmasq", restart_service: true
# Distributed search & analytics engine
brew "elasticsearch", restart_service: true
# Command-line fuzzy finder written in Go
brew "fzf"
# Easy semantic versioning for projects using Git
brew "gitversion"
# Interpreted, interactive, object-oriented programming language
brew "python", link: false
# Improved top (interactive process viewer)
brew "htop"
# Apache HTTP server
brew "httpd"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Drop-in replacement for MySQL
brew "mariadb", restart_service: true
# Mac App Store command-line interface
brew "mas"
# General-purpose scripting language
brew "php", link: false
# General-purpose scripting language
brew "php@7.2"
# General-purpose scripting language
brew "php@7.3"
# Programmer-oriented testing framework for PHP
brew "phpunit"
# Manage compile and link flags for libraries
brew "pkg-config"
# Visualize data generated by Cachegrind and Calltree
brew "qcachegrind"
# Ruby version manager
brew "rbenv"
# Persistent key-value database, with built-in net interface
brew "redis", restart_service: true
# Add a public key to a remote machine's authorized_keys file
brew "ssh-copy-id"
# Process Control System
brew "supervisor"
# C++ Unit Test Framework
brew "unittest"
# Internet file retriever
brew "wget"
# JavaScript package manager
brew "yarn"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# General-purpose scripting language
brew "exolnet/deprecated/php@5.6"
# General-purpose scripting language
brew "exolnet/deprecated/php@7.1", link: true
cask "alfred"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-awesome-terminal-fonts"
cask "font-fontawesome"
cask "font-hack-nerd-font"
cask "font-source-code-pro"
cask "google-chrome"
cask "grandperspective"
cask "iterm2"
cask "kap"
cask "postman"
cask "rowanj-gitx"
cask "spotify"
cask "sublime-text"
cask "transmit"
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
